name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - name: run python
      run: | 
         python -m pip install django  && copy . /app
         EXPOSE 8000
         CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
