name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run python
      RUN: python -m pip install django && WORKDIR /app && COPY . /app
      RUN: EXPOSE 8000
      RUN: CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
