name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
    - uses: actions/checkout@v2
    - name: run python
      run: python -m pip install django && WORKDIR /app && COPY . /app
      
    - name: run expose port 8080
      run: EXPOSE 8000
    - name: fireup app
      run: CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
