name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file https://raw.githubusercontent.com/sk3pp3r/yalla_suduku/main/app/Dockerfile --tag my-image-name:$(date +%s)
