name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: | 
          python -m pip install django && WORKDIR /app && COPY . /app
          EXPOSE 8000
          CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
